# Generated by Django 2.2 on 2020-09-21 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=30)),
                ('short_desc', models.CharField(max_length=120)),
                ('long_desc', models.TextField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(upload_to='images/article-images/')),
                ('uploaded_file', models.FileField(upload_to='documents/article-documents/')),
                ('subject', models.CharField(choices=[('ASF', 'Asfalt'), ('AST', 'Assistent'), ('BES', 'Bestratingen'), ('BET', 'Betonboren')], default='ASF', max_length=3)),
                ('level', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4')], default=1)),
                ('file_type', models.CharField(choices=[('3DB', '3D-beeld'), ('ANI', 'Animaties'), ('DID', 'Didactische werkvorm'), ('GRO', '(Groeps)opdracht'), ('PRE', 'Presentatie'), ('TOE', 'Toets'), ('NVT', 'N.v.t.')], default='3DB', max_length=3)),
                ('is_public', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('downloads', models.ManyToManyField(blank=True, null=True, related_name='user_downloads', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='articles.Tag')),
                ('user_likes', models.ManyToManyField(blank=True, null=True, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikelen',
            },
        ),
    ]
