# Generated by Django 2.2 on 2020-10-01 14:50

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/article-images', verbose_name='articleimg'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_file',
            field=models.FileField(upload_to='documents/article-documents', verbose_name='articledoc'),
        ),
    ]
