# Generated by Django 2.2 on 2020-10-15 13:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201015_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[40, 40], upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='images/article-images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='documents/article-documents'),
        ),
    ]
