# Generated by Django 2.2 on 2020-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201022_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.IntegerField(choices=[(1, 'Iedereen mag dit zien'), (0, 'Alleen voor leden op dit platform')], default=1),
        ),
    ]
